# Usamos la imagen oficial de PHP 8.0 con Apache
FROM php:8.0-apache

# Copiamos el contenido de nuestra carpeta local 'src' al directorio del servidor
COPY src/ /var/www/html/

# Exponemos el puerto 80
EXPOSE 80